# Generated by Django 5.2.17 on 2026-09-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('abuse', 'Оскорбление'), ('illegal', 'Незаконный контент'), ('offtopic', 'Оффтоп'), ('other', 'Другое')], max_length=16)),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewed', 'Рассмотрена'), ('dismissed', 'Отклонена'), ('actioned', 'Приняты меры')], db_index=True, default='new', max_length=16)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.post')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'), models.Index(fields=['post'], name='moderation__post_id_fb782a_idx')],
            },
        ),
    ]
