# Generated by Django 5.2.17 on 2026-09-10 11:09

import apps.forum.models
import apps.forum.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be 2-32 characters: lowercase letters, digits, hyphens and underscores; must start with a letter or digit.', regex='^[a-z0-9][a-z0-9_-]{1,31}$')])),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='forum_board_is_acti_690399_idx')],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('bumped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forum.board')),
            ],
            options={
                'ordering': ('-is_pinned', '-bumped_at'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(validators=[apps.forum.validators.validate_post_body])),
                ('is_op', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('poster_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.thread')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.forum.models.attachment_upload_path, validators=[apps.forum.validators.AttachmentValidator()])),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.post')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['post'], name='forum_attac_post_id_382bf7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['board', '-bumped_at'], name='forum_threa_board_i_5abe7c_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['is_hidden', '-bumped_at'], name='forum_threa_is_hidd_d41e47_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='forum_post_thread__a619d5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_hidden'], name='forum_post_is_hidd_9e3152_idx'),
        ),
    ]
