# Generated by Django 5.2.17 on 2026-09-10 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=128)),
                ('source_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('original_url', models.URLField(blank=True, default='', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('allowed', 'Разрешено'), ('rejected', 'Отклонено'), ('used', 'Использовано')], db_index=True, default='pending', max_length=16)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of title+body for deduplication.', max_length=64)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-added_at',),
                'indexes': [models.Index(fields=['source_name', 'source_identifier'], name='platinum_so_source__c78081_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatinumStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('source_type', models.CharField(blank=True, default='', help_text="Free-form origin tag, e.g. 'dvach', 'custom'.", max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сгенерировано'), ('approved', 'Одобрено'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=16)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platinum_stories', to='platinum.sourcestory')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='platinum_pl_status_04209e_idx')],
            },
        ),
    ]
